<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.3.0-dev10301709</Version>
        <Title>Injection Expert</Title>
        <Authors>Pygmalions</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>A dependency injection library based on dynamic IL weaving.</Description>
        <PackageProjectUrl>https://github.com/Pygmalions/InjectionExpert</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Pygmalions/InjectionExpert</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>IoC DI Dependency-Injection Injector-Generator IL-Emitting</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="EmitToolbox" Version="0.3.0-dev09102111" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    </ItemGroup>
    
    <Target Name="InjectPackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec" Condition="Exists('RELEASE_NOTE.txt')">
        <PropertyGroup>
            <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/RELEASE_NOTE.txt"))</PackageReleaseNotes>
        </PropertyGroup>
    </Target>
</Project>
